/*
 * $HeadURL$
 * $Revision$
 * $Date$
 * 
 * ====================================================================
 *
 *  Copyright 1999-2004 The Apache Software Foundation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals on behalf of the Apache Software Foundation.  For more
 * information on the Apache Software Foundation, please see
 * <http://www.apache.org/>.
 *
 */

package org.apache.http;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

/**
 * Unit tests for {@link NameValuePair}.
 *
 * @author <a href="mailto:oleg at ural.ru">Oleg Kalnichevski</a>
 */
public class TestHeader extends TestCase {

    public TestHeader(String testName) {
        super(testName);
    }

    public static void main(String args[]) {
        String[] testCaseName = { TestHeader.class.getName() };
        junit.textui.TestRunner.main(testCaseName);
    }

    public static Test suite() {
        return new TestSuite(TestHeader.class);
    }

    public void testConstructor() {
        Header header = new Header("name", "value", true);
        assertEquals("name", header.getName()); 
        assertEquals("value", header.getValue()); 
        assertTrue(header.isAutogenerated()); 
    }
    
    public void testInvalidName() {
        try {
            Header header = new Header(null, null);
            fail("IllegalArgumentException should have been thrown");
        } catch (IllegalArgumentException ex) {
            //expected
        }
    }
    
    public void testHashCode() {
        Header header1 = new Header("name1", "value1");
        Header header2 = new Header("name2", "value2");
        Header header3 = new Header("name1", "value1");
        assertTrue(header1.hashCode() != header2.hashCode());
        assertTrue(header1.hashCode() == header3.hashCode());
    }
    
    public void testEquals() {
        Header header1 = new Header("name1", "value1");
        Header header2 = new Header("name2", "value2");
        Header header3 = new Header("name1", "value1");
        assertFalse(header1.equals(header2));
        assertFalse(header1.equals(null));
        assertFalse(header1.equals("name1 = value1"));
        assertTrue(header1.equals(header1));
        assertTrue(header2.equals(header2));
        assertTrue(header1.equals(header3));
    }
    
    public void testToString() {
        Header header1 = new Header("name1", "value1");
        assertEquals("name1: value1", header1.toString());
    }
    
    public void testHeaderElements() {
        Header header = new Header("name", "element1 = value1, element2; param1 = value1, element3");
        HeaderElement[] elements = header.getElements(); 
        assertNotNull(elements); 
        assertEquals(3, elements.length); 
        assertEquals("element1", elements[0].getName()); 
        assertEquals("value1", elements[0].getValue()); 
        assertEquals("element2", elements[1].getName()); 
        assertEquals(null, elements[1].getValue()); 
        assertEquals("element3", elements[2].getName()); 
        assertEquals(null, elements[2].getValue()); 
        assertEquals(1, elements[1].getParameters().length); 
    }    
    
    public void testHeaderParsing() throws Exception {
        Header header1 = Header.parse("name:value"); 
        assertEquals("name", header1.getName());
        assertEquals("value", header1.getValue());

        Header header2 = Header.parse("    name   :    value       "); 
        assertEquals("name", header2.getName());
        assertEquals("value", header2.getValue());
        
        try {
            Header header3 = Header.parse("  whatever  ");
            fail("ProtocolException should have been thrown");
        } catch (ProtocolException ex) {
            // expected
        }

        try {
            Header header3 = Header.parse(null);
            fail("IllegalArgumentException should have been thrown");
        } catch (IllegalArgumentException ex) {
            // expected
        }
    }    
}
